### ISSUE TITLE
Modularity to Resume update

### ISSUE THREAD

**Issue by harshit7rathore** [vinayak19th/vinayak19th.github.io#8]
https://github.com/vinayak19th/vinayak19th.github.io/blob/08d0bacdc4a74d9a92f096e8b224554303a14530/_includes/intro.html#L4

This could be made more modular by replacing it with {{ site.resume | escape }} 

https://github.com/vinayak19th/vinayak19th.github.io/blob/08d0bacdc4a74d9a92f096e8b224554303a14530/_config.yml#L8

and adding resume: link after website link

**Comment by vinayak19th** [comment]
Did you test this on mobile devices?

**Comment by vinayak19th** [comment]
Will intregrate this in
